### ISSUE TITLE
Representation of single / double changes in .NET Core 3

### ISSUE THREAD

**Issue by jaredpar** [dotnet/metadata-tools#30]
The default representation of single, doubles and decimals changed in .NET Core 3.0. Specifically the precision changed. This means that `ToString` will return different results depending on whether the code is running on .NET Core or .NET Desktop.

The code in `DumpILBlock` needs to be updated to account for this to make IL visualization of constants sane on tests that multi-target between .NET Core and .NET Desktop.

Post explaining the breaks: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by tmat** [comment]
We display floats and doubles using the raw bytes in Pdb2Xml:

```C#
"0x" + BitConverter.DoubleToInt64Bits(d).ToString("X16"), // display the underlying raw bytes to ensure display independent of platform (core/netfx)
```

Is that reasonable solution for DumpILBlock as well?

**Comment by jaredpar** [comment]
The approach we've been using is `"G7"` for single and `"G15"` for doubles. That's what @tannergooding post recommended. 

Really though any representation which is equal between desktop and corelr will be sufficient. Already going to have to re-baseline a lot of tests so not really concerned what the new baseline is as long as it's consistent between the runtimes.

**Comment by tmat** [comment]
When I tried this before for Pdb2Xml I remember we concluded that G7/G15 is not guaranteed to be the same. Hence I opted for displaying raw bytes.

**Comment by tannergooding** [comment]
`"G7"` and `"G15"` are the previous formats used for `float.ToString()` and `double.ToString()` respectively. Outside of a few rare edge cases (generally midpoint values), the results returned for this between .NET Core and Full Framework should be the same.

That being said, `"G7"` and `"G15"` will generally not produce roundtrippable values which may be important for some scenarios (you wouldn't want to display `Math.PI` in the IDE and have it parse to something slightly different).

Displaying the raw underlying bits will be consistent across both platforms and might be sufficient for some tests.

**Comment by tmat** [comment]
Thanks for the details. I think I'm gonna go with raw bits, so that we have reliable tests and don't run into problems with "a few rare edge cases (generally midpoint values)".
